swagger: "2.0"
info:
  description: Swagger for Rest API
  version: "1.0.0"
  title: Ticket Manager Service
consumes:
  - application/json
produces:
  - application/json

basePath: /aiops

# Paths supported by the server application
paths:
  /insert/student:
    post:
      tags:
      - "INSERT"
      summary: "insert operation"
      description: "insert operation"
      operationId: orm.insert1  #method name in the main file
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
        - name: class_id
          in: formData
          type: integer
          required: True
        - name: created_on
          in: formData
          type: string
          required: True
        - name: updated_on
          in: formData
          type: string
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string



  /insert/class:
    post:
      tags:
      - "INSERT"
      summary: "insert operation"
      description: "insert operation"
      operationId: orm.insert2 #method name in the main file
      parameters:
        - name: id
          in: formData
          type: integer
          required: True
        - name: name
          in: formData
          type: string
          required: True
        - name: class_leader
          in: formData
          type: string
          required: True
        - name: created_on
          in: formData
          type: string
          required: True
        - name: updated_on
          in: formData
          type: string
          required: True
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string


  /read/student:
    get:
      tags:
      - "READ"
      summary: "read opearation"
      description: "read opearation"
      operationId: orm.read1
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string


  /read/class:
    get:
      tags:
        - "READ"
      summary: "read opearation"
      description: "read opearation"
      operationId: orm.read2
      responses:
        500:
          description: Server error
        200:
          description: Successful
          schema:
            type: string
